@api = http://localhost:4000/api/v1

### Products
GET {{api}}

###Getting all products
GET {{api}}/products

###Getting all products by query
GET {{api}}/products?categories=5ff7ae3605c7a82a8cb70669,5ff7ac4923cfde141c8465d5


###Getting one product
GET {{api}}/product/5ffba353c2fd0c2170283537

###
GET {{api}}/products/get/count
###
GET {{api}}/products/get/featured/2
###sending a product
POST {{api}}/products
Content-Type: application/json

{
  "name": "Modern Warfare",    
    "description": "Use this to play some war games",
    "richDescription": "",    
    "image": "urle",
    "brand": "Xbox",
    "price": 30,
    "category": "5ff7ac4923cfde141c8465d5",    
    "stock": 1,
    "rating":0,
    "numReviews": 0,
    "isFeatured": false
}

### Deleting a product
DELETE {{api}}/products/5ffba353c2fd0c2170283537

###Updating a product
PUT {{api}}/products/5ff7b3c8f450843dc489741f
Content-Type: application/json

{
    "name": "Apple",    
    "description": "eat it",
    "richDescription": "",    
    "image": "urle",
    "brand": "SOriana",
    "price": 30,
    "category": "5ff7a1c2bd82052c0c383849",    
    "stock": 1,
    "rating":0,
    "numReviews": 0,
    "isFeatured": true
}

###Users
GET {{api}}/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZlMjIzMWZlZjM2ZjNhZjQzYzlhM2MiLCJpYXQiOjE2MTA0OTUwNjYsImV4cCI6MTYxMDU4MTQ2Nn0.11-DYF86zEi6wxUkHDbQXjOSDzGSgR8L7_RrZikR2NQ
###Creation
POST {{api}}/users/signUp
Content-Type: application/json

{
    "name": "pedro",
    "email": "sleeping@gmail.com",
    "password": "sleep",
    "phone": "3319666859",
    "isAdmin": true,
    "street": "Delaware st",
    "apartment": "44A",
    "zip": "44970",
    "city": "Guadalajara",
    "country": "Mexico"
}

### Sign in

POST {{api}}/users/signIn
Content-Type: application/json

{
    "email": "marcel@gmail.com",
    "password": "john10"
}


###Categories
GET {{api}}/categories

###create a Category
POST {{api}}/categories
Content-Type: application/json

{
    "name": "",
    "color": "#102",
    "icon": "xfasd10"
}

###
DELETE  {{api}}/categories/5ff7a10d9eaf9a138ca0d07f


###
PUT {{api}}/categories/5ff7a1c2bd82052c0c383845
Content-Type: application/json

{
    "name": "Supplies",
    "color": "#103"    
}
### Orders


### OrderItems

